Feat/api
wallace41290/trucking-kit pull request #28
Opened 2024-01-17 18:05 UTC by nmrichards

Added amplify api.

2024-01-19 01:01 UTC, wallace41290 commented
<img width="877" alt="Screen Shot 2024-01-18 at 7 58 31 PM" src="https://github.com/wallace41290/trucking-kit/assets/11969737/bccafb6a-40ec-4e8d-a805-d0fb653a9b2f">
You've got a failure in the pipeline, when it just spits out files, I think that's usually the formatted complaining. You should be able to locally run `npm run pr-check` to produce the same results and fix issues.
1. the nested vscode settings can be deleted
2. the graphql schema either needs to be formatted or put in the prettierignore

`npm run format` will try to automatically format files

2024-01-19 01:12 UTC, wallace41290 requested changes

2024-01-19 01:12 UTC, wallace41290 commented on apps/trucking-kit/.vscode/settings.json
delete this file

2024-01-19 01:12 UTC, wallace41290 commented on apps/trucking-kit/.eslintignore
not sure what this is. do we need it? if you delete it and then run the linter, does it still pass?

2024-01-19 01:12 UTC, wallace41290 commented on AWSCLIV2.pkg
I don't think we need this in git, can you delete?

2024-01-19 01:12 UTC, wallace41290 commented on libs/trucking-kit/companies/companies.component.ts
For now, can you just move these files to:
`libs/trucking-kit/home/feature-home/src/lib/companies/companies.component.{ts,html,css}`

and keep it in the same feature-home lib for now?

2024-01-19 01:14 UTC, wallace41290 commented on apps/trucking-kit/amplify/backend/api/truckingkit/schema.graphql
Did we decide to leave the user for now? Let's try to keep this PR as slim as possible

2024-01-19 15:48 UTC, nmrichards commented on apps/trucking-kit/amplify/backend/api/truckingkit/schema.graphql
With this, if we don't have a user, how do ensure the Company/user relationship? Are you able to establish the relationship within Cognito alone? Either by storing the company information within the user or user information within the company (or maybe both)?

2024-01-19 15:48 UTC, nmrichards commented on apps/trucking-kit/amplify/backend/api/truckingkit/schema.graphql
I'm looking into this as I really don't know. Maybe they do some backend magic to link those two together easier?

2024-01-20 20:40 UTC, wallace41290 submitted a review, later dismissed
LGTM

2024-01-29 20:20 UTC, merged